[package]
name = "x11-dl"
version = "2.17.3"
authors = ["Daggerbot <daggerbot@gmail.com>"]
description = "X11 library bindings for Rust"
license = "CC0-1.0"
repository = "https://github.com/Daggerbot/x11-rs.git"
build = "build.rs"
documentation = "https://docs.rs/x11-dl"
workspace = ".."

[dependencies]
lazy_static = "1"
libc = "0.2"

[build-dependencies]
pkg-config = "0.3.8"
